# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql
  pool: 5
  timeout: 5000
  database: <%= PRIVATE['db']['name'] %>
  username: <%= PRIVATE['db']['user'] %>
  password: <%= PRIVATE['db']['pass'] %>
  host: <%= PRIVATE['db']['host'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
